# SPDX-FileCopyrightText: 2020-2023 CERN
# SPDX-FileCopyrightText: 2023 GSI Helmholtzzentrum für Schwerionenforschung
# SPDX-FileNotice: All rights not expressly granted are reserved.
#
# SPDX-License-Identifier: GPL-3.0-or-later OR EUPL-1.2+

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: check-toml
  - id: check-yaml
    args: ["--unsafe"]
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/fsfe/reuse-tool
  rev: v2.1.0
  hooks:
    - id: reuse
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.6.1
  hooks:
  - id: mypy
    exclude: ^docs/conf.py
    args: [--strict]
    additional_dependencies:
    - git+https://gitlab.cern.ch/geoff/cernml-coi@v0.8.13
    - git+https://gitlab.cern.ch/geoff/cernml-coi-optimizers@v1.1.0
    - pytest
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.1.3
  hooks:
    - id: ruff-format
    - id: ruff
      args: [ --fix, --exit-non-zero-on-fix ]
